# coding: utf-8

"""
    MagicBell REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import magicbell
from magicbell.api.real_time_api import RealTimeApi  # noqa: E501
from magicbell.rest import ApiException


class TestRealTimeApi(unittest.TestCase):
    """RealTimeApi unit test stubs"""

    def setUp(self):
        self.api = magicbell.api.real_time_api.RealTimeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_notification(self):
        """Test case for create_notification

        Create notifications  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
