# coding: utf-8

"""
    MagicBell REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import magicbell
from magicbell.models.notifications import Notifications  # noqa: E501
from magicbell.rest import ApiException

class TestNotifications(unittest.TestCase):
    """Notifications unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Notifications
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = magicbell.models.notifications.Notifications()  # noqa: E501
        if include_optional :
            return Notifications(
                project_id = 56, 
                total = 56, 
                per_page = 56, 
                total_pages = 56, 
                current_page = 56, 
                unseen_count = 56, 
                unread_count = 56, 
                notifications = [
                    magicbell.models.notification.Notification(
                        title = '', 
                        category = '', 
                        content = '', 
                        action_url = '', 
                        recipients = [
                            magicbell.models.recipient.Recipient(
                                email = '', 
                                external_id = '', 
                                matches = '', )
                            ], 
                        custom_attributes = { }, 
                        topic = '', 
                        overrides = magicbell.models.notification_overrides.Notification_overrides(
                            channels = magicbell.models.notification_overrides_channels.Notification_overrides_channels(
                                in_app = magicbell.models.channel_overrides.ChannelOverrides(
                                    title = '', 
                                    content = '', 
                                    action_url = '', ), 
                                email = magicbell.models.channel_overrides.ChannelOverrides(
                                    title = '', 
                                    content = '', 
                                    action_url = '', ), 
                                web_push = , 
                                mobile_push = , ), 
                            providers = magicbell.models.notification_overrides_providers.Notification_overrides_providers(
                                sendgrid = magicbell.models.sendgrid.sendgrid(), 
                                mailgun = magicbell.models.mailgun.mailgun(), 
                                postmark = magicbell.models.postmark.postmark(), 
                                ios = magicbell.models.ios.ios(), 
                                android = magicbell.models.android.android(), ), ), )
                    ]
            )
        else :
            return Notifications(
        )

    def testNotifications(self):
        """Test Notifications"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
