# coding: utf-8

"""
    MagicBell REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import magicbell
from magicbell.models.notification_overrides import NotificationOverrides  # noqa: E501
from magicbell.rest import ApiException

class TestNotificationOverrides(unittest.TestCase):
    """NotificationOverrides unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test NotificationOverrides
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = magicbell.models.notification_overrides.NotificationOverrides()  # noqa: E501
        if include_optional :
            return NotificationOverrides(
                channels = magicbell.models.notification_overrides_channels.Notification_overrides_channels(
                    in_app = magicbell.models.channel_overrides.ChannelOverrides(
                        title = '', 
                        content = '', 
                        action_url = '', ), 
                    email = magicbell.models.channel_overrides.ChannelOverrides(
                        title = '', 
                        content = '', 
                        action_url = '', ), 
                    web_push = , 
                    mobile_push = , ), 
                providers = magicbell.models.notification_overrides_providers.Notification_overrides_providers(
                    sendgrid = magicbell.models.sendgrid.sendgrid(), 
                    mailgun = magicbell.models.mailgun.mailgun(), 
                    postmark = magicbell.models.postmark.postmark(), 
                    ios = magicbell.models.ios.ios(), 
                    android = magicbell.models.android.android(), )
            )
        else :
            return NotificationOverrides(
        )

    def testNotificationOverrides(self):
        """Test NotificationOverrides"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
