# coding: utf-8

"""
    MagicBell REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import magicbell
from magicbell.models.create_notification422_response import (
    CreateNotification422Response,
)  # noqa: E501
from magicbell.rest import ApiException


class TestCreateNotification422Response(unittest.TestCase):
    """CreateNotification422Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test CreateNotification422Response
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # model = magicbell.models.create_notification422_response.CreateNotification422Response()  # noqa: E501
        if include_optional:
            return CreateNotification422Response(
                errors=[
                    magicbell.models.create_notification_422_response_errors_inner.create_notification_422_response_errors_inner(
                        message="",
                    )
                ]
            )
        else:
            return CreateNotification422Response()

    def testCreateNotification422Response(self):
        """Test CreateNotification422Response"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
