# general mkdocs config
site_name: MagicBell Python SDK
nav:
  - Home: index.md
  - Examples:
      - 'Setup': examples/index.md
      - 'Getting Started': examples/01 - Getting Started.ipynb
      - 'Users': examples/02 - Users.ipynb
      - 'Projects': examples/03 - Projects.ipynb
      - 'GraphQL': examples/04 - GraphQL.ipynb
  - Reference:
      - 'MagicBell': reference/magicbell-client.md
      - 'Configuration': reference/configuration.md
      - 'RealtimeAPI': reference/realtime-api.md
      - 'UserAPI': reference/user-api.md
      - 'ProjectAPI': reference/project-api.md
      - 'GraphQLAPI': reference/graphql-api.md
repo_url: https://github.com/noteable-io/magicbell-python-sdk
repo_name: noteable-io/magicbell-python-sdk
edit_uri: edit/main/docs/

# Material theme config
theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: slate
  features:
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#instant-loading
    - navigation.instant


# plugins
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: 'numpy'
  - mkdocs-jupyter:
      include_source: True

markdown_extensions:
  # code highlighting
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/noteable_io
    - icon: fontawesome/brands/github
      link: https://github.com/noteable-io
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/noteable-io/
    - icon: fontawesome/brands/medium
      link: https://medium.com/noteableio
