# coding: utf-8

# flake8: noqa
"""
    MagicBell REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from magicbell.models.channel_overrides import ChannelOverrides
from magicbell.models.create_notification201_response import (
    CreateNotification201Response,
)
from magicbell.models.create_notification422_response import (
    CreateNotification422Response,
)
from magicbell.models.create_notification422_response_errors_inner import (
    CreateNotification422ResponseErrorsInner,
)
from magicbell.models.created_notification_broadcast import CreatedNotificationBroadcast
from magicbell.models.created_push_subscription import CreatedPushSubscription
from magicbell.models.notification import Notification
from magicbell.models.notification_broadcast import NotificationBroadcast
from magicbell.models.notification_overrides import NotificationOverrides
from magicbell.models.notification_overrides_channels import (
    NotificationOverridesChannels,
)
from magicbell.models.notification_overrides_providers import (
    NotificationOverridesProviders,
)
from magicbell.models.notification_preferences import NotificationPreferences
from magicbell.models.notification_preferences_categories import (
    NotificationPreferencesCategories,
)
from magicbell.models.notifications import Notifications
from magicbell.models.push_subscription import PushSubscription
from magicbell.models.recipient import Recipient
from magicbell.models.user import User
from magicbell.models.user_preferences_category import UserPreferencesCategory
from magicbell.models.wrapped_notification import WrappedNotification
from magicbell.models.wrapped_notification_preferences import (
    WrappedNotificationPreferences,
)
from magicbell.models.wrapped_push_subscription import WrappedPushSubscription
from magicbell.models.wrapped_user import WrappedUser
