# coding: utf-8

"""
    MagicBell REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from magicbell.configuration import Configuration


class ChannelOverrides(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {"title": "str", "content": "str", "action_url": "str"}

    attribute_map = {"title": "title", "content": "content", "action_url": "action_url"}

    def __init__(
        self, title=None, content=None, action_url=None, local_vars_configuration=None
    ):  # noqa: E501
        """ChannelOverrides - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._title = None
        self._content = None
        self._action_url = None
        self.discriminator = None

        if title is not None:
            self.title = title
        if content is not None:
            self.content = content
        if action_url is not None:
            self.action_url = action_url

    @property
    def title(self):
        """Gets the title of this ChannelOverrides.  # noqa: E501

        Overriden title for this channel  # noqa: E501

        :return: The title of this ChannelOverrides.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this ChannelOverrides.

        Overriden title for this channel  # noqa: E501

        :param title: The title of this ChannelOverrides.  # noqa: E501
        :type title: str
        """

        self._title = title

    @property
    def content(self):
        """Gets the content of this ChannelOverrides.  # noqa: E501

        Overriden content for this channel  # noqa: E501

        :return: The content of this ChannelOverrides.  # noqa: E501
        :rtype: str
        """
        return self._content

    @content.setter
    def content(self, content):
        """Sets the content of this ChannelOverrides.

        Overriden content for this channel  # noqa: E501

        :param content: The content of this ChannelOverrides.  # noqa: E501
        :type content: str
        """

        self._content = content

    @property
    def action_url(self):
        """Gets the action_url of this ChannelOverrides.  # noqa: E501

        Overriden action_url for this channel  # noqa: E501

        :return: The action_url of this ChannelOverrides.  # noqa: E501
        :rtype: str
        """
        return self._action_url

    @action_url.setter
    def action_url(self, action_url):
        """Sets the action_url of this ChannelOverrides.

        Overriden action_url for this channel  # noqa: E501

        :param action_url: The action_url of this ChannelOverrides.  # noqa: E501
        :type action_url: str
        """

        self._action_url = action_url

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(lambda x: convert(x), value))
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(lambda item: (item[0], convert(item[1])), value.items())
                )
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ChannelOverrides):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ChannelOverrides):
            return True

        return self.to_dict() != other.to_dict()
