# coding: utf-8

"""
    MagicBell REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from magicbell.configuration import Configuration


class NotificationBroadcast(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        "title": "str",
        "recipients": "list[Recipient]",
        "category": "str",
        "topic": "str",
        "content": "str",
        "action_url": "str",
        "custom_attributes": "dict(str, object)",
    }

    attribute_map = {
        "title": "title",
        "recipients": "recipients",
        "category": "category",
        "topic": "topic",
        "content": "content",
        "action_url": "action_url",
        "custom_attributes": "custom_attributes",
    }

    def __init__(
        self,
        title=None,
        recipients=None,
        category=None,
        topic=None,
        content=None,
        action_url=None,
        custom_attributes=None,
        local_vars_configuration=None,
    ):  # noqa: E501
        """NotificationBroadcast - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._title = None
        self._recipients = None
        self._category = None
        self._topic = None
        self._content = None
        self._action_url = None
        self._custom_attributes = None
        self.discriminator = None

        self.title = title
        self.recipients = recipients
        if category is not None:
            self.category = category
        if topic is not None:
            self.topic = topic
        if content is not None:
            self.content = content
        if action_url is not None:
            self.action_url = action_url
        self.custom_attributes = custom_attributes

    @property
    def title(self):
        """Gets the title of this NotificationBroadcast.  # noqa: E501

        Overriden action_url  # noqa: E501

        :return: The title of this NotificationBroadcast.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this NotificationBroadcast.

        Overriden action_url  # noqa: E501

        :param title: The title of this NotificationBroadcast.  # noqa: E501
        :type title: str
        """
        if (
            self.local_vars_configuration.client_side_validation and title is None
        ):  # noqa: E501
            raise ValueError(
                "Invalid value for `title`, must not be `None`"
            )  # noqa: E501

        self._title = title

    @property
    def recipients(self):
        """Gets the recipients of this NotificationBroadcast.  # noqa: E501

        Recipients of the notification  # noqa: E501

        :return: The recipients of this NotificationBroadcast.  # noqa: E501
        :rtype: list[Recipient]
        """
        return self._recipients

    @recipients.setter
    def recipients(self, recipients):
        """Sets the recipients of this NotificationBroadcast.

        Recipients of the notification  # noqa: E501

        :param recipients: The recipients of this NotificationBroadcast.  # noqa: E501
        :type recipients: list[Recipient]
        """
        if (
            self.local_vars_configuration.client_side_validation and recipients is None
        ):  # noqa: E501
            raise ValueError(
                "Invalid value for `recipients`, must not be `None`"
            )  # noqa: E501

        self._recipients = recipients

    @property
    def category(self):
        """Gets the category of this NotificationBroadcast.  # noqa: E501

        Category the notification belongs to  # noqa: E501

        :return: The category of this NotificationBroadcast.  # noqa: E501
        :rtype: str
        """
        return self._category

    @category.setter
    def category(self, category):
        """Sets the category of this NotificationBroadcast.

        Category the notification belongs to  # noqa: E501

        :param category: The category of this NotificationBroadcast.  # noqa: E501
        :type category: str
        """

        self._category = category

    @property
    def topic(self):
        """Gets the topic of this NotificationBroadcast.  # noqa: E501

        Topic the notification belongs to  # noqa: E501

        :return: The topic of this NotificationBroadcast.  # noqa: E501
        :rtype: str
        """
        return self._topic

    @topic.setter
    def topic(self, topic):
        """Sets the topic of this NotificationBroadcast.

        Topic the notification belongs to  # noqa: E501

        :param topic: The topic of this NotificationBroadcast.  # noqa: E501
        :type topic: str
        """

        self._topic = topic

    @property
    def content(self):
        """Gets the content of this NotificationBroadcast.  # noqa: E501

        Content of the notification  # noqa: E501

        :return: The content of this NotificationBroadcast.  # noqa: E501
        :rtype: str
        """
        return self._content

    @content.setter
    def content(self, content):
        """Sets the content of this NotificationBroadcast.

        Content of the notification  # noqa: E501

        :param content: The content of this NotificationBroadcast.  # noqa: E501
        :type content: str
        """

        self._content = content

    @property
    def action_url(self):
        """Gets the action_url of this NotificationBroadcast.  # noqa: E501

        A URL to redirect the user to when they click the notification in their notification inbox.  # noqa: E501

        :return: The action_url of this NotificationBroadcast.  # noqa: E501
        :rtype: str
        """
        return self._action_url

    @action_url.setter
    def action_url(self, action_url):
        """Sets the action_url of this NotificationBroadcast.

        A URL to redirect the user to when they click the notification in their notification inbox.  # noqa: E501

        :param action_url: The action_url of this NotificationBroadcast.  # noqa: E501
        :type action_url: str
        """

        self._action_url = action_url

    @property
    def custom_attributes(self):
        """Gets the custom_attributes of this NotificationBroadcast.  # noqa: E501

        Set of key-value pairs that you can attach to a notification  # noqa: E501

        :return: The custom_attributes of this NotificationBroadcast.  # noqa: E501
        :rtype: dict(str, object)
        """
        return self._custom_attributes

    @custom_attributes.setter
    def custom_attributes(self, custom_attributes):
        """Sets the custom_attributes of this NotificationBroadcast.

        Set of key-value pairs that you can attach to a notification  # noqa: E501

        :param custom_attributes: The custom_attributes of this NotificationBroadcast.  # noqa: E501
        :type custom_attributes: dict(str, object)
        """

        self._custom_attributes = custom_attributes

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(lambda x: convert(x), value))
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(lambda item: (item[0], convert(item[1])), value.items())
                )
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NotificationBroadcast):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, NotificationBroadcast):
            return True

        return self.to_dict() != other.to_dict()
