# coding: utf-8

"""
    MagicBell REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from magicbell.configuration import Configuration


class NotificationOverrides(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        "channels": "NotificationOverridesChannels",
        "providers": "NotificationOverridesProviders",
    }

    attribute_map = {"channels": "channels", "providers": "providers"}

    def __init__(
        self, channels=None, providers=None, local_vars_configuration=None
    ):  # noqa: E501
        """NotificationOverrides - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._channels = None
        self._providers = None
        self.discriminator = None

        if channels is not None:
            self.channels = channels
        if providers is not None:
            self.providers = providers

    @property
    def channels(self):
        """Gets the channels of this NotificationOverrides.  # noqa: E501


        :return: The channels of this NotificationOverrides.  # noqa: E501
        :rtype: NotificationOverridesChannels
        """
        return self._channels

    @channels.setter
    def channels(self, channels):
        """Sets the channels of this NotificationOverrides.


        :param channels: The channels of this NotificationOverrides.  # noqa: E501
        :type channels: NotificationOverridesChannels
        """

        self._channels = channels

    @property
    def providers(self):
        """Gets the providers of this NotificationOverrides.  # noqa: E501


        :return: The providers of this NotificationOverrides.  # noqa: E501
        :rtype: NotificationOverridesProviders
        """
        return self._providers

    @providers.setter
    def providers(self, providers):
        """Sets the providers of this NotificationOverrides.


        :param providers: The providers of this NotificationOverrides.  # noqa: E501
        :type providers: NotificationOverridesProviders
        """

        self._providers = providers

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(lambda x: convert(x), value))
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(lambda item: (item[0], convert(item[1])), value.items())
                )
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NotificationOverrides):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, NotificationOverrides):
            return True

        return self.to_dict() != other.to_dict()
