# coding: utf-8

"""
    MagicBell REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from magicbell.configuration import Configuration


class UserPreferencesCategory(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        "email": "bool",
        "in_app": "bool",
        "mobile_push": "bool",
        "web_push": "bool",
    }

    attribute_map = {
        "email": "email",
        "in_app": "in_app",
        "mobile_push": "mobile_push",
        "web_push": "web_push",
    }

    def __init__(
        self,
        email=None,
        in_app=None,
        mobile_push=None,
        web_push=None,
        local_vars_configuration=None,
    ):  # noqa: E501
        """UserPreferencesCategory - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._email = None
        self._in_app = None
        self._mobile_push = None
        self._web_push = None
        self.discriminator = None

        if email is not None:
            self.email = email
        if in_app is not None:
            self.in_app = in_app
        if mobile_push is not None:
            self.mobile_push = mobile_push
        if web_push is not None:
            self.web_push = web_push

    @property
    def email(self):
        """Gets the email of this UserPreferencesCategory.  # noqa: E501

        A flag to enable or disable email messages for this category when a new notification is created.  # noqa: E501

        :return: The email of this UserPreferencesCategory.  # noqa: E501
        :rtype: bool
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this UserPreferencesCategory.

        A flag to enable or disable email messages for this category when a new notification is created.  # noqa: E501

        :param email: The email of this UserPreferencesCategory.  # noqa: E501
        :type email: bool
        """

        self._email = email

    @property
    def in_app(self):
        """Gets the in_app of this UserPreferencesCategory.  # noqa: E501

        Whether to send new notifications to the notification inbox or not.  # noqa: E501

        :return: The in_app of this UserPreferencesCategory.  # noqa: E501
        :rtype: bool
        """
        return self._in_app

    @in_app.setter
    def in_app(self, in_app):
        """Sets the in_app of this UserPreferencesCategory.

        Whether to send new notifications to the notification inbox or not.  # noqa: E501

        :param in_app: The in_app of this UserPreferencesCategory.  # noqa: E501
        :type in_app: bool
        """

        self._in_app = in_app

    @property
    def mobile_push(self):
        """Gets the mobile_push of this UserPreferencesCategory.  # noqa: E501

        A flag to enable or disable mobile push notifications for this category when a new notification is created.  # noqa: E501

        :return: The mobile_push of this UserPreferencesCategory.  # noqa: E501
        :rtype: bool
        """
        return self._mobile_push

    @mobile_push.setter
    def mobile_push(self, mobile_push):
        """Sets the mobile_push of this UserPreferencesCategory.

        A flag to enable or disable mobile push notifications for this category when a new notification is created.  # noqa: E501

        :param mobile_push: The mobile_push of this UserPreferencesCategory.  # noqa: E501
        :type mobile_push: bool
        """

        self._mobile_push = mobile_push

    @property
    def web_push(self):
        """Gets the web_push of this UserPreferencesCategory.  # noqa: E501

        A flag to enable or disable browser push notifications for this category when a new notification is created.  # noqa: E501

        :return: The web_push of this UserPreferencesCategory.  # noqa: E501
        :rtype: bool
        """
        return self._web_push

    @web_push.setter
    def web_push(self, web_push):
        """Sets the web_push of this UserPreferencesCategory.

        A flag to enable or disable browser push notifications for this category when a new notification is created.  # noqa: E501

        :param web_push: The web_push of this UserPreferencesCategory.  # noqa: E501
        :type web_push: bool
        """

        self._web_push = web_push

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(lambda x: convert(x), value))
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(lambda item: (item[0], convert(item[1])), value.items())
                )
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserPreferencesCategory):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, UserPreferencesCategory):
            return True

        return self.to_dict() != other.to_dict()
